### PR TITLE
Keep version and relese synced with downstream

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by omron93** [comment]
@hhorak @pkubatrh Can't this cause some problems for already build/pushed images?

**Comment by pkubatrh** [comment]
No issues for rhel based images since this is what was already used in them. For centos ones I have no idea.

But we should keep them in sync (rhel vs. centos) in any case.

**Comment by omron93** [comment]
So rhel image internally is built with version 1. But centos image in Docker Hub has tag 10.2. So after several improvements in this repo, latest image will have tag 1 but it will be confusing because there would be image with tag 10.2.
So I am thinking about removing the 10.2 image from Docker Hub. @pkubatrh @hhorak Ideas?

**Comment by hhorak** [comment]
I'm definitely for keeping the versions in sync, and if removing the image is possible from docker hub, let's do it. If it is not, I can live with that... Most people should use `:latest` tag anyway.

**Comment by hhorak** [comment]
Thanks for the PR, merging.

**Comment by omron93** [comment]
> I'm definitely for keeping the versions in sync, and if removing the image is possible from docker hub, let's do it. If it is not, I can live with that...

It is possible - remove image from docker hub. And then push image (with right tag) again. Unfortunately I don't know Hub credentials to be able to do it.

**Comment by hhorak** [comment]
It is also possible to remove the tag through web UI, so it's solved now.

**Comment by omron93** [comment]
Thanks.

**Pull request merged**
