### PR TITLE
[WIP] s2i and general extendability support

### PR DESCRIPTION
**Pull request by hhorak**
This implements a similar approach to extend the image either using s2i, or by mounting the extending files into `/opt/app-root`. It also adds some OpenShift tests, together with `test-lib-openshift.sh` that should be moved to https://github.com/sclorg/container-common-scripts/.

### CODE REVIEW

**Comment by hhorak** [comment]
As @TomasTomecek suggested in #32, we should document extending images in the Dockerfile, so one can e.g. change USER to 0 to be able to install RPMs..

**Comment by hhorak** [comment]
We should also include an SSL example as part of the documentatoin/test.

**Comment by TomasTomecek** [comment]
@mkocka promised he would review this PR

**Comment by mkocka** [comment]
[mkocka@warp mariadb-container]$ make build TARGET=centos7 VERSIONS=10.1
make[1]: Entering directory '/home/mkocka/work/mariadb-container'
mkdir -p 10.1/root
go-md2man -in "10.1/README.md" -out "10.1/root/help.1"
/bin/sh: go-md2man: command not found
make[1]: *** [common/common.mk:80: 10.1/root/help.1] Error 127
make[1]: Leaving directory '/home/mkocka/work/mariadb-container'
make: *** [common/common.mk:42: build-serial] Error 2

I am having trouble to test this, see ^^ 
I am using right branch, up to date: 

[mkocka@warp mariadb-container]$ git branch
  master
* s2i-support-3

**Comment by TomasTomecek** [comment]
```
/bin/sh: go-md2man: command not found
```

You should install the package: `golang-github-cpuguy83-go-md2man`

**Comment by omron93** [comment]
@mkocka Or you can run `make build TARGET=centos7 VERSIONS=10.1 SKIP_SQUASH=1`

**Comment by mkocka** [comment]
Testing s2i mount
chown: changing ownership of '/tmp/tmp.V1N7QPOHRE/test-app/mysql-data/init.sql': Operation not permitted
... This problem occurred for several files in that folder 

Tests failed.
make: *** [common/common.mk:63: test] Error 1

**Comment by hhorak** [comment]
@mkocka what permission the '/tmp/tmp.V1N7QPOHRE/test-app/mysql-data/init.sql' file has?

**Comment by hhorak** [comment]
[test]

**Comment by omron93** [comment]
[test]

**Pull request merged**
