### PR TITLE
Add note about MariaDB and MySQL similarity

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
#dotests

**Comment by hhorak** [comment]
#dotests

**Comment by hhorak** [comment]
#dotests

**Comment by hhorak** [comment]
#dotests

**Comment by hhorak** [comment]
#dotest

**Comment by hhorak** [comment]
#dotest

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
#dotest

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
Closed in favor of #6.

**Comment by omron93** [comment]
[test]

**Pull request closed without merging**
