### PR TITLE
Add aarch64 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by phracek** [comment]
I don't see any issue here. Let's try to test it.

[test][test-openshift]

**Comment by hhorak** [comment]
Import works.

**Comment by hhorak** [comment]
The tests likely fail because of outdated common/ sub-module. Merging anyway, I've checked manually.

**Pull request merged**
