### PR TITLE
Support testing on OpenShift-4

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds the possibility to test mariadb-container on OpenShift 4 remote cluster
via the external registry, where is pushed the image after the build.

### CODE REVIEW

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift-4]

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by hhorak** [comment]
LGTM

**Pull request merged**
