### PR TITLE
Added extension point 

### PR DESCRIPTION
**Pull request by andreasschramm**
Hi, please consider adding extension points for users.

### CODE REVIEW

**Comment by hhorak** [comment]
Thanks for the contribution, we had several discussions about how to make this generally and it currently seems like using s2i approach might be better, see #34 for more details.

**Comment by andreasschramm** [comment]
I was about to ask about that, i have seen your pull request, and agree it might be a better approach. 
I have yet to find out the best way to do some other things, yum and whatever.

**Comment by hhorak** [comment]
Sorry, my previous comment mentioned #34, but I wanted to point to #32.. but you probably found the right one.. I've also added an example of a Dockerfile that changes USER and thus can install additional packages -- https://github.com/hhorak/mariadb-container/blob/s2i-support/10.1/test/Dockerfile

**Comment by andreasschramm** [comment]
thanks, i was unsure on to how to do it "the right way", dockerfile or assemble. Still finding out the best  way to provide such functionality in a userfriendly way.

**Pull request closed without merging**
