### PR TITLE
add template icon

### PR DESCRIPTION
**Pull request by alfonsoalongi**
add template icon

### CODE REVIEW

**Comment by phracek** [comment]
@alfonsoalongi Thanks for this pull request. The pull request looks good to me.

@yselkowitz Does it work? Please let me know.

**Comment by alfonsoalongi** [comment]
> @alfonsoalongi Thanks for this pull request. The pull request looks good to me.
> 
> @yselkowitz Does it work? Please let me know.

Hi,
yes it works. I checked it on OpenShift Container Platform 4.7 but not on OKD. I attached a screenshot about the graphical result.
mariadb-icon

**Comment by yselkowitz** [comment]
Didn't have a chance to try it yet, but it's just a label, so why not.  We should look at the rest of the templates and try (testing and) adding similar flags.

**Comment by alfonsoalongi** [comment]
I think so too. Yes, I also tried similar annotations with the other database templates.
For MySQL: https://github.com/sclorg/mysql-container/pull/300
For PostgreSQL: https://github.com/sclorg/postgresql-container/pull/409
I can also check other icons for other templates but feedbacks to pull requests on github repositories come too late. This pull request dates back to May 25 (almost 7 months ago).

**Comment by yselkowitz** [comment]
LGTM

**Comment by phracek** [comment]
[test-all]

**Pull request merged**
