### PR TITLE
templates: omit version/tag 10.0 from description

### PR DESCRIPTION
**Pull request by pvalena**
https://github.com/openshift/origin/pull/17922#discussion_r160709178

### CODE REVIEW

**Comment by omron93** [comment]
[test] [test-openshift]

**Comment by pvalena** [comment]
This is a description change and does not affect runtime in any way. And tests succeeded. Merging.

**Comment by omron93** [comment]
Mariadb 10.0 is still supported. @pvalena Why to remove it from template?

**Comment by pvalena** [comment]
@omron93, templates are for OpenShift, right? And Mariadb 10.0 is not in OpenShift.

See https://github.com/openshift/origin/pull/17922#discussion_r160709178.

**Comment by omron93** [comment]
> @omron93, templates are for OpenShift, right? And Mariadb 10.0 is not in OpenShift.

I've read this. But the fact that "there's no mariadb:10.0 tag" don't imply that the tag shouldn't be there. 

I've found in OpenShift docs that 'rhscl/mariadb-100-rhel7' is supported! - https://docs.openshift.com/container-platform/3.7/using_images/db_images/mariadb.html

**Pull request merged**
