### PR TITLE
Support 10.5 for building on RHEL7 and CentOS7

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for RHEL7 and CentOS7 for version 10.5.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
@pkubatrh @zmiklank Please if you have time, please look at it.

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
The Openshift tests fails because we do not yet have the image in the quay.io registries. We only push into the registries when an image is build after a PR is merged, so we first need to merge this PR with failing Openshift test before the Openshift tests can pass.
#158 Will then check if the tests are passing when the quay.io registry has the image and follow up on any further failures encountered

**Pull request merged**
